### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by wargamesqcf** [Morgul/rpgkeeper#18]
How do I build/use this?

Will this work for Legend of the Five Rings 4th edition?

Do you have any experience with implementing a dice roller into rocket.chat?

**Comment by Morgul** [comment]
In order:

1) You will need node.js installed. Once you have that, you will need to install bower and grunt: `npm install -g bower grunt`. Then it's just a simple:
* `npm install`
* `bower install`
* `grunt`
* `npm start`

The reason I don't have these instructions up is because the main use case of this is to use it online, at [rpgkeeper.com](rpgkeeper.com).

2) I'm not familiar with either of those games; I don't have any systems built for those. You can try the generic system, and see if that has enough tools for you.

3) Yes, actually. It was a pretty straightforward little project, just built an express website that adhered to the [Outgoing Webhooks](https://api.slack.com/outgoing-webhooks) api. I'd recommend using my other library [rpgdice](https://github.com/Morgul/rpgdice) to power the rolls, but that's just me. ;)

**Comment by wargamesqcf** [comment]
sadly not robust enough for the l5r system, going to use hubot with a custom script to handle dice on chat, already have a super cool forums chatroller. http://five-rings-online.com/forums/showthread.php?tid=9

but keep it need more open source rpg stuff.
