### ISSUE TITLE
Skill buy

### ISSUE THREAD

**Issue by wargamesqcf** [Morgul/rpgkeeper#21]
Is it possible to add in a skill buy system?

So I want to go from skill 6 to 7 it would cost 7 exp?

Does rpgkeeper have a good way of handing out exp like 4-5 every sunday?

**Comment by Morgul** [comment]
For background, it's important to realize that each system has it's own rules (and, in fact, it's own code), so what the D&D system does doesn't necessarily need to be the same as what the Edge of the Empire system does. So, while currently no system implements a point buy, that doesn't mean one _couldn't_ be implemented.

Generally, these are concerns I try to leave to the player. Starting with point buy, I've played plenty of games where the GM has allowed me to buy at a reduced rate, due to backstory or other roleplaying related concerns. It technically violated the rules, but I've never played with a group that didn't have a house rule or two. So to implement a point-buy, you'd need some way to override the cost. Why not just let the player manage it like they would a paper sheet? I'm not opposed to the idea, just wary about the complexity to handle these cases.

Regarding the handing out of XP, this is even more compounded of a problem. What if you skip a Sunday? What if your GM gives you more/less this time around? What if your session didn't go as normal, and you spent the entire time in a jail, staring at the wall, therefore earned no XP? I'm very resistant to any sort of automation with regards to handing out XP.

Here's a good example; in my D&D games, I use an alternate house rule. We have 'Character Points' as opposed to XP. Normally, my players would be getting several hundred XP per session, instead they get 1 to 2 CP, as voted on at the end of the session. How is RPGKeeper supposed to know about this alternate house rule and work appropriately? I feel it's just easier for the player to update a number in a form, frankly.

**Comment by wargamesqcf** [comment]
The way I wish to implement this is for a RP site based around legend of the five rings, we currently have everyone make a character sheet on the forums, make them a sub forums and update each sheet manually. My group have 100+ characters and 40-50 really active players.

**Comment by Morgul** [comment]
I'm closing this; but there's something important here.

Many systems have rules for leveling up characters, and some groups have house rules for leveling up. _It is not possible for RPGKeeper to support arbitrary rules, or all possible rules per system._ However, that doesn't mean that we shouldn't support the most common level up rules, and allow the community to add whichever levelup rules they want to for the system.

So, at the end of the day, this item should turn into a request for the "Legend of the Five Rings" system, and an extension to Core to allow for level-up rules, with `manual` always being allowed.
