### ISSUE TITLE
Release for user testing?

### ISSUE THREAD

**Issue by PiotrZakrzewski** [Morgul/rpgkeeper#50]
Hi!

Amazing project, I always wanted to build a character inventory like this! I pulled the code and started it locally, but somehow I cannot get character creation working, it fails with 
```Failed to parse permissions for account 1: SyntaxError: Unexpected token * in JSON at position 1```
could you recommend a tag/release/commit I could use to do some end user testing?

cheers!
PS: If I wrap my head around the code I might contribute WFRP 4ed support

**Comment by Morgul** [comment]
Hey! Great to see someone excited about it!

So, master is kept in a "runnable state" as best as possible. I'm working on updating the deployments; master will end up being pushed out to https://beta.rpgkeeper.com whenever we merge, that way it'll be easier for people to test out new features.

The problem here seems to be initial database connection and first time user login. Since I have a DB I've created a while ago, I don't test it that often. I will see about doing some work this weekend and see if I can't track down the bug, and push up a fix.

Also, I will be working on a brief overview of the project layout to help with new people working on it; I was asked about this by a friend who wants to contribute, so seems like a good idea all around!

In the meantime, you might try taking a look at the database it generated. I suspect that whatever string value is in `accounts.permissions` is wrong. It should be `['*/*']`, I believe. You can try making it null, though, to see if that lets it run.

**Comment by Morgul** [comment]
Hey, @PiotrZakrzewski, fixed the issue with master! Feel free to keep reporting bugs, and keep an eye peeled for the new docs and probably a conversion to typescript in the near future. (That should help with onboarding as well, it's a lot clearer when you can trace through the code a bit better.)

(Fixed in d91e39f97bec5142c37e17b4e93aa21d64fd5a52.)
